name: ESLint Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Run ESLint
        run: |
          npm install eslint
          npx eslint src/scripts/**/*.js --fix
